#!/bin/bash


#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=lamma
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:30:00
#SBATCH --mem=16000M
#SBATCH --output=jobs/slurm_output/train_llama_%A.out


module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/dl4nlp/Multi-Turn-Dialogue-Reasoning
source activate nlp
python -u $HOME/dl4nlp/Multi-Turn-Dialogue-Reasoning/train_llama.py 